### PR TITLE
upload of all country datasets (137 MB)

### PR DESCRIPTION
**Pull request by floriandierickx**
it might be practical for people to head to the specific csv files for their country of interest (considering the 137 MB reasonable, hoping that the server storage won't affect climate change more than it helps other people :p )

### CODE REVIEW

**Comment by mikapfl** [comment]
I think with 137 MB, git is already quite impractical. I'll set up a [datalad](https://www.datalad.org/) dataset with the data. That has the added benefit that metadata can be provided easily etc.

**Comment by floriandierickx** [comment]
Ok I see, interesting.. I'm discovering interesting tools thanks to you!

**Comment by mikapfl** [comment]
I have converted the repository to a datalad dataset, and added the data on gin (see the README). Unfortunately, github large file storage is pretty limited (1 GB of bandwidth per month even in the github pro tier), so people have to get the data from gin.

**Comment by floriandierickx** [comment]
Cool, that will come in handy. In any case, it will be very valuable for people to have access to the full breakdown of the UNFCCC database time series in one file, I'll be the first to make use of it! To my knowledge, I did not (yet) discover another database like this. Maybe the PRIMAP-hist database [[github link](https://github.com/JGuetschow/PRIMAP-hist/blob/master/README.md), [PIK visualisation](https://www.pik-potsdam.de/paris-reality-check/primap-hist/), [dataset](https://www.pik-potsdam.de/paris-reality-check/primap-hist/data/HISTCR_EARTH_KYOTOGHGAR4_Mt.csv)] from @JGuetschow ? At first sight this is a dataset of the 5 main sectors, but maybe I overlooked something.

**Comment by floriandierickx** [comment]
And of course the [unfccc-detailed-data-by-party](https://github.com/JGuetschow/unfccc-detailed-data-by-party) from @openclimatedata and @JGuetschow, but when I tried to [tingle with the script to extend the categories](https://github.com/floriandierickx/unfccc-detailed-data-by-party) I managed to get myself into a month waiting time :-p

**Comment by mikapfl** [comment]
And of course, there is also https://www.pik-potsdam.de/paris-reality-check/primap-crf/ . We will see if we can produce an updated version of primap-crf using this dataset.

**Comment by JGuetschow** [comment]
I think we should be able to do that. but I have not looked at the downloaded data in detail, so there might be surprises.

**Pull request closed without merging**
